import {Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;

export const Colors = {
  shadow_color: '#000',
  modalText_color: '#3B3B3B',
  statusbarcolor: '#dc9827',
  appColor_border: '#E7B278',
  trans_txt: '#0B0B0B',
  //appColor: '#D9862A',
  appColor: '#dc9827',
  green: '#19BD3C',
  blue: '#0075FF',
  edit_profile_txt_color: '#181818',
  terms_condi_txt: '#151515',
  signup_text_title: '#474747',
  signup_placeholder_color: '#858585',
  internetbackcolor: '#dc9827',
  login_btn_color: '#dc9827',
  onlinebackcolor: '#6082DA',
  internettextcolor: '#FFFFFF',
  onlinetextcolor: '#FFFFFF',
  mediabackground: '#FFFFFF',
  mediatextcolor: 'black',
  cancletextcolor: 'black',
  buttoncolor: '#20e003',
  whiteColor: '#FFFFFF',
  greyColor: 'gray',
  Otpresedcolor: 'green',
  otpcountcolor: 'red',
  facebook: '#1985ff',
  white_color: '#fff',
  header_top: '#f5f5f5',
  white_light_color: '#b8b8b8',
  black_color: '#000',
  button_color: '#dc9827',
  statusbar_color: '#dc9827',
  page_indicatore: '#c3c3c3',
  gray_color: '#D2D0D0',
  textcolor: '#A3A3A3',
  main_font: '#dc9827',
  fontcolor: '#79573e',
  button_border: '#77543b',
  textColors: '#7f7d7d',
  imagebackcolor: '#d6d6d6',
  placeholdetext: '#7f7d7d',
  placeholderborder: '#cd7474',
  header_top: '#dc9827',
  pass_bottom_border: '#868686',
  allmsg: '#7F7F7F',
  //    allmag:'#959090',
  search_text: '#F8F8F8',
  Light_border: '#f4f4f4',
  box_border: '#f7f7f7',
  pendingColor: '#F2C802',
  grayborder: '#C6C6C6',
  editbutton: '#0999C1',
  lightcolor: '#F7F6F6',
  bottom_border: '#D0D7DE',
  blue_color: '#1fb6ff',
  login: '#01C6FC',
  lightskyblue: '#DEF8FF',
  Liner_top: '#01A3EE',
  Liner_bottom: '#023EC7',
  light_grey: '#CFCFCF',
  red: '#FF0000',
  textBlack_color: '#000',

  ///////////Atul Colors////////////
};
export const Font = {
  theme_color: '#D9862A',
  fontmedium: 'Inter-Medium',
  fontitalic: 'Nunito-Italic',
  //fontsemiitalic: 'Nunito-SemiBoldItalic',
  fontbold: 'Inter-Bold',
  fontregular: 'Inter-Regular',
  fontextrabold: 'Inter-ExtraBold',
  fontthin: 'Inter-Thin',
  fontextralight: 'Inter-ExtraLight',
  fontlight: 'Inter-Light',
  fontblack: 'Inter-Black',
  fontsemibold: 'Inter-SemiBold',
  headerfamily: 'Inter-SemiBold',
  placeholderstyle: 'Inter-Regular',
  button_font: 'Inter-SemiBold',
  fontsizetermcondition: (windowWidth * 2.7) / 100,
  button_size: (windowWidth * 3.5) / 100,
  placeholdersize: (windowWidth * 3.5) / 100,
  serachplaceholdersize: (windowWidth * 4) / 100,
  headerfont: (windowWidth * 5) / 100,
  headingfont: (windowWidth * 4.5) / 100,
  search_size: (windowWidth * 4) / 100,
};
